//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotPizzaApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Ansatt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ansatt()
        {
            this.Pizza = new HashSet<Pizza>();
        }
    
        public int Id { get; set; }
        [Required(ErrorMessage = "Fornavn må fyllast inn")]
        public string Fornavn { get; set; }
        [Required(ErrorMessage = "Etternavn må fyllast inn")]
        public string Etternavn { get; set; }
        [Required(ErrorMessage = "Mobilnummer må fyllast inn")]
        public Nullable<int> Mobil { get; set; }
        public string BildeSrc { get; set; }
        [Required(ErrorMessage = "Avdeling må fyllast inn")]
        public Nullable<int> AvdelingId { get; set; }
        [Required(ErrorMessage = "Rolle må fyllast inn")]
        public Nullable<int> RolleId { get; set; }
        [Required]
        public string Brukernavn { get; set; }
        [Required]
        public string Passord { get; set; }
    
        public virtual Avdeling Avdeling { get; set; }
        public virtual Rolle Rolle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pizza> Pizza { get; set; }
    }
}
