//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotPizzaApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Henvendelse
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "Navn må fyllast inn")]
        public string Navn { get; set; }
        [Required(ErrorMessage = "Epost må fyllast inn")]
        public string Epost { get; set; }
        [Required(ErrorMessage = "Tittel må fyllast inn")]
        public string Tittel { get; set; }
        [Required(ErrorMessage = "Tekst må fyllast inn")]
        public string Tekst { get; set; }
    }
}
