//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotPizzaApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotPizzaDBEntities : DbContext
    {
        public HotPizzaDBEntities()
            : base("name=HotPizzaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ansatt> Ansatt { get; set; }
        public virtual DbSet<Avdeling> Avdeling { get; set; }
        public virtual DbSet<Henvendelse> Henvendelse { get; set; }
        public virtual DbSet<Pizza> Pizza { get; set; }
        public virtual DbSet<Rolle> Rolle { get; set; }
    }
}
